Rent_Scholar/config/routes.rb
 RentScholar::Application.routes.draw do
  resources :listings

  root :to => 'listings#index'

end

Rent_Scholar/app/models/landlord.rb
class Landlord < ActiveRecord::Base
 
  attr_accessible :email, :password_hash, :password_salt
 
  has_many :listings

end

Rent_Scholar/app/models/listing.rb
class Listing < ActiveRecord::Base
  
  attr_accessible :address, :confirmed, :description, :price, :title, :rooms, :landlord_id
  
  validates :title, :address, :price, :rooms, :presence => true
  
  belongs_to :landlord
 
end

Rent_Scholar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Rent_Scholar/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end
end

Rent_Scholar/app/helpers/application_helper.rb
module ApplicationHelper
end

Rent_Scholar/app/helpers/listings_helper.rb
module ListingsHelper
end

Rent_Scholar/app/views/layouts/application.html.erb
<%= render 'shared/before_title' %>
    <title>RentScholar</title>
      <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag 'modernizr' %>

  <!-- Initializes the modernizr and actually perform the checks. Enable this
       if you need the modernizr, but remember to only do the actual checks
       that you need. -->
  <%= javascript_tag "Modernizr.load();" %>
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <%= render 'shared/nav' %>

  <div id='content' class='row'>
	  <div class="large-10 columns">
    <%= yield %>
  </div>
	
  <!-- JavaScript at the bottom for fast page loading: http://developer.yahoo.com/performance/rules.html#js_bottom -->
  <%= javascript_include_tag 'application' %>

  <% if Rails.env.production? %>
  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
  <% end %>
</body>
</html>

Rent_Scholar/app/views/listings/_form.html.erb
<%= form_for @listing, :html => { :class => 'form-horizontal' } do |f| %>

  <% @listing.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
  <% end %>
	
  <%= f.label :rooms %>
    <%= f.select(:rooms, options_for_select([['1 bedroom', 1], ['2 bedrooms', 2], ['3 bedrooms', 3]])) %> 

    <%= f.label :title %>   
      <%= f.text_field :title %>

    <%= f.label :description %>
      <%= f.text_area :description %>   

    <%= f.label :address %>
      <%= f.text_field :address %>

    <%= f.label :price %>
      <%= f.text_field :price %>  

    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                listings_path, :class => 'btn' %>

<% end %>

Rent_Scholar/app/views/listings/edit.html.erb
<%- model_class = Listing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

Rent_Scholar/app/views/listings/index.html.erb
<%- model_class = Listing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
	   <th><%= model_class.human_attribute_name(:rooms) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
	  <th><%= model_class.human_attribute_name(:landlord_id) %></th>  
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to listing.id, listing_path(listing) %></td>
        <td><%= listing.title %></td>
        <td><%= listing.description %></td>
        <td><%= listing.address %></td>
	    <td><%= listing.address %></td>
        <td><%= listing.price %></td>
		<td><%= listing.landlord_id %></td>
        <td><%=l listing.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_listing_path(listing), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      listing_path(listing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_listing_path,
            :class => 'btn btn-primary' %>

Rent_Scholar/app/views/listings/new.html.erb
<%- model_class = Listing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

Rent_Scholar/app/views/listings/show.html.erb
<%- model_class = Listing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @listing.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @listing.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rooms) %>:</strong></dt>
  <dd><%= @listing.rooms %></dd> 
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @listing.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @listing.price %></dd>

</dl>

<div class="form-actions">
	
  <%= link_to t('.back', :default => t("helpers.links.back")),
              listings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_listing_path(@listing), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              listing_path(@listing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

Rent_Scholar/app/views/shared/_before_title.html.erb
<!doctype html>
  
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  

Rent_Scholar/app/views/shared/_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="/">RentScholar.com</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon">
		<a href="#"><span></span></a>
	</li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><a href="#">Log in</a></li>       
    </ul>
  </section>
</nav>