RentScholar/config/routes.rb
RentScholar::Application.routes.draw do
  
  resources :listings, :only => [:index, :new, :create, :destroy]

  devise_for :landlords, :controllers => {:confirmations => 'confirmations'}

  devise_scope :landlord do
    put "/confirm" => "confirmations#confirm"
  end

  get "welcome/home"
    
  match "welcome/list" => "welcome#list", :as => 'list'
  
  match "dashboard/index" => "dashboard#index", :as => 'dashboard'

  root :to => 'welcome#home'

end

RentScholar/app/models/landlord.rb
class Landlord < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  # attr_accessible :title, :body  
  has_many :listings
  validates :listing, :presence => true
  devise :database_authenticatable, :registerable, :token_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable      
  attr_accessible :email, :password, :password_confirmation, :remember_me, :listings_attributes
  
  # Include default devise modules. Others available are:
  # 
  # and :omniauthable
  
  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end
  
  def new
    @landlord = Landlord.new
    @landlord.listings.build
  end
  
end

RentScholar/app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :landlord  
  attr_accessible :title, :description, :rooms, :price, :available, :utilities, :address, :city, :province, :country, :images
end

RentScholar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 
  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

RentScholar/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_landlord!
  def index
    @landlord_email = current_landlord.email
  end
end

RentScholar/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  def new
    @listing = Listing.new
    @listing.landlords.build
  end
  
  def create
    @listing = Listing.new(params[:listing])
    if @listing.save
      flash[:success] = "Listing created"
      redirect_to root_path
    else
      render 'new'
    end
  end
end

RentScholar/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
  
  def list
  end
  
end

RentScholar/app/helpers/application_helper.rb
module ApplicationHelper
end

RentScholar/app/helpers/dashboard_helper.rb
module DashboardHelper
end

RentScholar/app/helpers/welcome_helper.rb
module WelcomeHelper
end

RentScholar/app/views/dashboard/index.html.slim
p Signed in as #{@landlord_email}
=link_to('Logout', destroy_landlord_session_path, :method => :delete)  

h1 Dashboard

h2 Your Listing(s)  

RentScholar/app/views/layouts/application.html.slim
doctype html
/[if lt IE 7]
  |<html class='no-js lt-ie9 lt-ie8 lt-ie7'>
/[if IE 7]
  |<html class='no-js lt-ie9 lt-ie8'>
/[if IE 8]
  |<html class='no-js lt-ie9'>
/![if gt IE 8]><!
html.no-js
  /!<![endif]

  = render 'head'

  body
    
    = render 'chromeframe'
   
    = render 'header'

    = render 'flashes'

    = yield

    = render 'footer'

    / Javascript at the bottom for fast page loading
    = render 'javascripts'

RentScholar/app/views/listings/new.html.erb
<h2>Create Listing</h2>

<%= form_for(@listing) do |f| %>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <%= fields_for :landlords do |landlord_form| %>
  <div class="field">
    <%= landlord_form.label :email %><br />
    <%= landlord_form.email_field :email %>
  </div>
  <% end %>
   
  <div class="actions"> 
    <%= f.submit "Create Listing" %>
  </div>
  
<% end %>

RentScholar/app/views/welcome/home.html.slim
h1 Welcome Home
p Ohhh, yeahhh. Railsss yeahhhh.

= link_to "List", new_landlord_registration_path 
// = link_to "List", new_listing_path
br 
= link_to "Dashboard", dashboard_path

RentScholar/app/views/welcome/list.html.slim
h1 List it
p chyeaah